/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ModuleModel } from "./ModuleModel";
import { ModuleModelCountArgs } from "./ModuleModelCountArgs";
import { ModuleModelFindManyArgs } from "./ModuleModelFindManyArgs";
import { ModuleModelFindUniqueArgs } from "./ModuleModelFindUniqueArgs";
import { CreateModuleModelArgs } from "./CreateModuleModelArgs";
import { UpdateModuleModelArgs } from "./UpdateModuleModelArgs";
import { DeleteModuleModelArgs } from "./DeleteModuleModelArgs";
import { AssignmentFindManyArgs } from "../../assignment/base/AssignmentFindManyArgs";
import { Assignment } from "../../assignment/base/Assignment";
import { Course } from "../../course/base/Course";
import { ModuleModelService } from "../moduleModel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ModuleModel)
export class ModuleModelResolverBase {
  constructor(
    protected readonly service: ModuleModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ModuleModel",
    action: "read",
    possession: "any",
  })
  async _moduleModelsMeta(
    @graphql.Args() args: ModuleModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ModuleModel])
  @nestAccessControl.UseRoles({
    resource: "ModuleModel",
    action: "read",
    possession: "any",
  })
  async moduleModels(
    @graphql.Args() args: ModuleModelFindManyArgs
  ): Promise<ModuleModel[]> {
    return this.service.moduleModels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ModuleModel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ModuleModel",
    action: "read",
    possession: "own",
  })
  async moduleModel(
    @graphql.Args() args: ModuleModelFindUniqueArgs
  ): Promise<ModuleModel | null> {
    const result = await this.service.moduleModel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ModuleModel)
  @nestAccessControl.UseRoles({
    resource: "ModuleModel",
    action: "create",
    possession: "any",
  })
  async createModuleModel(
    @graphql.Args() args: CreateModuleModelArgs
  ): Promise<ModuleModel> {
    return await this.service.createModuleModel({
      ...args,
      data: {
        ...args.data,

        course: args.data.course
          ? {
              connect: args.data.course,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ModuleModel)
  @nestAccessControl.UseRoles({
    resource: "ModuleModel",
    action: "update",
    possession: "any",
  })
  async updateModuleModel(
    @graphql.Args() args: UpdateModuleModelArgs
  ): Promise<ModuleModel | null> {
    try {
      return await this.service.updateModuleModel({
        ...args,
        data: {
          ...args.data,

          course: args.data.course
            ? {
                connect: args.data.course,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ModuleModel)
  @nestAccessControl.UseRoles({
    resource: "ModuleModel",
    action: "delete",
    possession: "any",
  })
  async deleteModuleModel(
    @graphql.Args() args: DeleteModuleModelArgs
  ): Promise<ModuleModel | null> {
    try {
      return await this.service.deleteModuleModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Assignment], { name: "assignments" })
  @nestAccessControl.UseRoles({
    resource: "Assignment",
    action: "read",
    possession: "any",
  })
  async findAssignments(
    @graphql.Parent() parent: ModuleModel,
    @graphql.Args() args: AssignmentFindManyArgs
  ): Promise<Assignment[]> {
    const results = await this.service.findAssignments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Course, {
    nullable: true,
    name: "course",
  })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "read",
    possession: "any",
  })
  async getCourse(
    @graphql.Parent() parent: ModuleModel
  ): Promise<Course | null> {
    const result = await this.service.getCourse(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
